### ISSUE TITLE
sort list of available perls

### ISSUE THREAD

**Issue by shawnlaffan** [stevieb9/berrybrew#101]
The releases.json file from the Strawberry perl site is sorted by date order, so 5.26.1 is listed between 5.24.3 and 5.22.3.  Berrybrew uses this order to list the available perls (see below), resulting in some cognitive dissonance when first checking the list.  

It would be very useful if the list of available perls were sorted alphabetically.  The orphaned and custom sets should still be at the end of the main list.  

```
C:\Users\user>berrybrew available

The following Strawberry Perls are available:

        5.24.3_64
        5.24.3_64_PDL
        5.24.3_32
        5.26.1_64
        5.26.1_64_PDL       [installed]
        5.26.1_32
        5.22.3_64
        5.22.3_64_PDL
        5.22.3_32
        5.20.3_64
        5.20.3_64_PDL
        5.20.3_32
        5.18.4_64
        5.18.4_32
        5.16.3_64
        5.16.3_32
        5.14.4_64
        5.14.4_32
        5.12.3_32
        5.10.1_32
        5.8.9_32
```

**Comment by stevieb9** [comment]
This is on my imminent to do list now.

Sample, working code to work from:

    string[] perlVersions = new string[] {
        "5.26.1_32", "5.12.3_32", "5.24.0_64", "5.26.0_64", "5.26.0_32"
    };
    Array.Sort(perlVersions);
    Array.Reverse(perlVersions);
    foreach (string str in perlVersions) Console.Write(str + " ");

Output:

    5.26.1_32 5.26.0_64 5.26.0_32 5.24.0_64 5.12.3_32

**Comment by stevieb9** [comment]
More appropriate code for our context:

    {
        List<string> perlVersions = new List<string>();

        perlVersions.Add("5.26.1_32");
        perlVersions.Add("5.24.1_32");
        perlVersions.Add("5.12.1_64");
        perlVersions.Add("5.24.2_64");
            
        perlVersions.Sort();
        perlVersions.Reverse();
        foreach (string str in perlVersions) Console.Write(str + " ");
    }
