### ISSUE TITLE
Add uninstall instructions in README

### ISSUE THREAD

**Issue by eliot1785** [stevieb9/berrybrew#106]
I first posted this question on StackOverflow (https://stackoverflow.com/q/50358559/783314) but remembered I could post it here. If I get an answer here I'll update that one.

How do you uninstall? I am hoping it is as simple as just deleting the directory where it was installed and C:\berrybrew, which is where it seems to keep files, but I don't know for sure. The instructions contain installation instructions, but no uninstallation instructions.

**Comment by stevieb9** [comment]
To "uninstall" berrybrew, you can do a:

berrybrew unconfig

...which'll remove Berrybrew and its associated Perl installations from
your path, then to remove it entirely, delete the original download
directory, as well as "c:\berrybrew".

Cheers,

Steve

**Comment by stevieb9** [comment]
If, by chance, you've removed the berrybrew directory before removing the
environment variable configurations, you can remove them from your
environment variable "PATH" as needed.
