### ISSUE TITLE
Support ActivePerl

### ISSUE THREAD

**Issue by jayvdb** [stevieb9/berrybrew#171]
Is it possible to use berrybrew with an existing preinstalled ActivePerl ?

The documentation reads as if this isnt possible.

If not, is it feasible to add this, or is berrybrew tightly coupled with StrawberryPerl , beyond install/switch/etc.

**Comment by stevieb9** [comment]
It's quite coupled with Strawberry, but you can use it with an
already-installed version of ActiveState.

The Perl in use with berrybrew preceeds any other Perl within your PATH
environment variable. To go back to ActiveState (or what I'd refer to as
the "system perl"), simply run "berrybrew off".

To go back to a berrybrew perl, use "berrybrew switch $version".

Let me know if this is what you meant or not. If you're wondering if
berrybrew can actually manage ActiveState Perl, the answer is no.

**Comment by jayvdb** [comment]
Thanks for replying.

> If you're wondering if berrybrew can actually manage ActiveState Perl, the answer is no.

Is it something you would active reject related PRs ?

As back-story, I would like to have an SOE where berrybrew and multiple StrawberryPerl is required for developers, however [AppVeyor CI provides ActiveState perl](https://www.appveyor.com/docs/windows-images-software/#perl) and installing Strawberry Perl on those VMs is quite time consuming, so I also need my scripts to also work with the ActiveState on their VMs.  I can keep the differences minimal if I add a layer like berrybrew.  Managing complexity of dependencies is a major concern for me, as I have a quite complicated grid of support for lots of languages.  e.g. two of our builds https://ci.appveyor.com/project/coala/package-manager/builds/25643827/job/ot1sbtikogd58iy5?fullLog=true / https://travis-ci.org/coala/coala-bears/builds/553771677

The commands which may be useful are `register` (to register the ActivePerl, but that may be unnecessary), `list` to get a parsable list of versions encompassing whatever ActiveState or StrawberryPerl are already installed, and of course `switch` to automate switching between them (but `use` would actually be much nicer if possible).  I dont mind if a lot of functionality is broken - the devs will be using StrawberryPerl, and the CI only needs to do a very small set of operations.  I can throw a bit of time towards this, if I know it isnt going to be discarded.

**Comment by stevieb9** [comment]
I'm definitely open to PRs for sure :)

I'm a bit busy over the next couple of days, but I'll do my best to get an
ActivePerl installed and see what the fallout is, and what kind of effort
we'll be looking at.

**Comment by stevieb9** [comment]
I'm finally back at it here. I just finished a contract for a client who wanted to switch over from ActiveState to Strawberry using berrybrew, so I've got a few testing VMs already set up.

I just finished making some sweeping changes to this project and am about to do a release. When that's done, I'm going to get to work on this.

My thinking is that AS won't work directly with berrybrew, but it may be possible for me to code something up to allow berrybrew to "use" a virtual perl (in this case the existing AS install).

Will update again when I've got something that may be tangibly workable.

**Comment by stevieb9** [comment]
I've got a tentative working solution for including ActiveState (and any external-to-berrybrew) Perls virtually. Have a look at my example run-through below and let me know if it's the sort of thing you're after? I'm currently just making some tweaks and writing documentation.

```
Configure an external Perl as a berrybrew-managed Perl ("active-state" is just a name you desire that'll show up in `berrybrew list` and `berrybrew available`):

    > berrybrew virtual active-state

    Specify the path to the perl binary: c:\perl64\bin

    Specify the library path: c:\perl64\site\bin

    Specify an additional path:


    Successfully registered virtual perl active-state
  
Check that it took:
   
    > berrybrew list
    
          5.16.3_64 *
          5.10.1_32 
          active-state
   
    > berybrew available

        ... snip for brevity

        5.16.3_64       [installed] *
        5.16.3_32
        5.14.4_64
        5.14.4_32
        5.12.3_64
        5.12.3_32
        5.10.1_32       [installed]
        5.8.9_32
        active-state    [virtual] [installed] 
                    
Verify we're still using the previous Perl:

    > perl -v

    This is perl 5, version 16, subversion 3 (v5.16.3) built for MSWin32-x64-multi-thread

Switch to the new one (NOTE: if you 'switch', you'll override the entire system, so your devs will run into issues):

    > berrybrew switch active-state

    Switched to Perl version active-state...

    Open a new command line window to use it 
    
Confirm we're using the actual Active State installation:

    > perl -v

    This is perl 5, version 26, subversion 3 (v5.26.3) built for MSWin32-x64-multi-thread
    (with 2 registered patches, see perl -V for more detail)

    Copyright 1987-2018, Larry Wall

    Binary build 0000 [fde9aa8a] provided by ActiveState http://www.ActiveState.com
    Built Jul 31 2019 01:43:08    
    
Use the Active State Perl in a way that will not modify global paths (ie. nobody else will be affected):

    ### verify we're using a non-Activestate Perl
    
    > perl -v

    This is perl 5, version 16, subversion 3 (v5.16.3) built for MSWin32-x64-multi-thread

    ### use ActiveState virtual perl
    
    > berrybrew use active-state
    
    perl-active-state
    ==============
    Microsoft Windows [Version 10.0.10240]
    (c) 2015 Microsoft Corporation. All rights reserved.


    <berrybrew use active-state>: run "exit" leave this environment

    ### verify we're using ActiveState Perl
    
    > perl -v

    This is perl 5, version 26, subversion 3 (v5.26.3) built for MSWin32-x64-multi-thread
    (with 2 registered patches, see perl -V for more detail)

    Copyright 1987-2018, Larry Wall

    Binary build 0000 [fde9aa8a] provided by ActiveState http://www.ActiveState.com
    Built Jul 31 2019 01:43:08

    ### once the new sub-shell is closed, confirm everything is sane
    
    > exit

    Exiting <berrybrew use active-state>


    > perl -v

    This is perl 5, version 16, subversion 3 (v5.16.3) built for MSWin32-x64-multi-thread
```

**Comment by stevieb9** [comment]
Implemented in version 1.26.

**Comment by jayvdb** [comment]
Very nice, thank you!

**Comment by stevieb9** [comment]
No problem.

Let me know if you have any questions or issues. I'll be glad to work with
you to improve the feature and/or documentation if necessary.
