### ISSUE TITLE
Unattended installation of berrybrew

### ISSUE THREAD

**Issue by sumanstats** [stevieb9/berrybrew#173]
Hi there,

During installation it asks for:
``Would you like to add berrybrew to PATH? y/n [n]``

It is perfectly fine in PC.

But while installing it in CI/CD services like appveyor, azure pipelines from command line, how can we install it? How can we install it **silently** with modification of path?

**Comment by stevieb9** [comment]
I will investigate and implement a method to have berrybrew install
silently over the next couple of days.

Perhaps adding a flag, or even removing the prompt entirely.

**Comment by stevieb9** [comment]
@sumanstats I have removed the prompt when running `berrybrew config`, so that it should install properly unattended. Version 1.25 which I released yesterday has this change.

**Comment by sumanstats** [comment]
Great. Thanks!
