### ISSUE TITLE
Avira false positive

### ISSUE THREAD

**Issue by nikosvaggalis** [stevieb9/berrybrew#241]
Hi and thanks for berrybrew! 
You might be interested to know that Avira identifies it as PUP,which of course is a false positive.
(check pic)
I'm letting you know in case you want to contact them to clear this up.
![avira_berry](https://user-images.githubusercontent.com/26706920/72761937-5272e600-3be6-11ea-82a2-16e70b799c0b.jpg)
thanks again

**Comment by rai-gaurav** [comment]
Not just avira , McAfee also showed this as PUA.

**Comment by rai-gaurav** [comment]
Just done a quick scan on Virus Total -
https://www.virustotal.com/gui/file/6256c7b89d08696c77fc17c6d6602ce8aad1a6229a7749a6448f15bc74b67101/detection
2 engines are detecting this sha.

**Comment by stevieb9** [comment]
Thanks for the report. I've reached out to the companies in hopes to get
the false positive detection fixed.

**Comment by rai-gaurav** [comment]
Just checked again at virus total - https://www.virustotal.com/gui/file/6256c7b89d08696c77fc17c6d6602ce8aad1a6229a7749a6448f15bc74b67101/detection
All the major vendors are not detecting it right now. I think this issue can be closed now.

**Comment by stevieb9** [comment]
Thank you for getting back to me on this. Closing.
