### ISSUE TITLE
Association error

### ISSUE THREAD

**Issue by TBSliver** [stevieb9/berrybrew#246]
Something since at least 1.29 means that in a non-privileged shell I get:

```
Changing file associations requires Administrator privileges
```

on every run of berrybrew. This completely breaks the integration with the Camelcade plugin with Intellij IDEA...

**Comment by stevieb9** [comment]
Thanks for the report. I will have a look a bit later on today.

**Comment by stevieb9** [comment]
> Something since at least 1.29 means that in a non-privileged shell I get:
> 
> ```
> Changing file associations requires Administrator privileges

> on every run of berrybrew. This completely breaks the integration with the Camelcade plugin with Intellij IDEA...

I've got all of my environments set back up after a long delay.

Is there any chance you could advise the version of Windows, version of the IDE and Camelcade, and what exactly you are doing when this issue occurs.

I've been a user of the IDE/plugin combo for numerous years, and I can't repro the issue reliably.
