### ISSUE TITLE
Can't run perl scripts from dirs with whitespace characters or cyrillic symbols in path 

### ISSUE THREAD

**Issue by svarogman** [stevieb9/berrybrew#285]
After installing berrybrew can't run perl scripts from dirs with whitespace characters or cyrillic symbols in path: 
`D:\>cd D:\temp\small test\`
`D:\temp\small test>test.pl`
`Can't open perl script "D:\temp\small": No such file or directory`

**Comment by stevieb9** [comment]
Thanks for reporting!

I'll have a look at this tomorrow.
