### ISSUE TITLE
SHA1 signature for version 1.35 executable has not been updated.

### ISSUE THREAD

**Issue by epronetlc** [stevieb9/berrybrew#307]
certutil -hashfile berrybrewInstaller.exe SHA1
SHA1 hash of berrybrewInstaller.exe:
7c9c82929a5198d9f9c672544d76449139a5d6ac
CertUtil: -hashfile command completed successfully.

**Comment by stevieb9** [comment]
Thank you for this. I will get this corrected this afternoon.

**Comment by stevieb9** [comment]
This was in fact a result of the release process going badly. The file
itself is confirmed valid.

**Comment by epronetlc** [comment]
Thanks for the quick reply.

 

Thank you,

 

Corey Collins

---

Corey Collins

IT Director | eProcessing Network, LLC

***@***.*** ***@***.***> 

Office: 713-880-0327 x 109 | Direct: 713-867-8450

Fax: 713-880-0330 | Cell: 713-444-0318

Technical Support: 800-971-0997

***@***.*** ***@***.***> 



CONFIDENTIALITY NOTE:

This transmission may contain information that is privileged, confidential, and/or exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is STRICTLY PROHIBITED. If you received this transmission in error, please immediately contact the sender and destroy the material in its entirety, whether in electronic or hard copy format.
