### ISSUE TITLE
Readme: perltricks.com domain no longer hosts the perltricks site

### ISSUE THREAD

**Issue by shawnlaffan** [stevieb9/berrybrew#313]
I'm not sure what it should be updated to, but the URL is no longer the perltricks site.  

https://github.com/stevieb9/berrybrew/blob/1cbe596dcb6de907687d8ce6c7199bffb1405a28/README.md?plain=1#L281

**Comment by stevieb9** [comment]
Thank you. I'll speak to David and see what do to here.

**Comment by stevieb9** [comment]
Fixed in 1.38
