### ISSUE TITLE
Crash trying to use config (unhandled exception writing Machine PATH without admin privs)

### ISSUE THREAD

**Issue by cmfrolick** [stevieb9/berrybrew#39]
I get an error trying to call config from a non-admin command prompt. Since manipulating the path probably requires elevated privileges, it probably should always check and warn if not run with correct privileges.

C:\berrybrew\bin>berrybrew.exe config

This is berrybrew, version
1.04

Would you like to add berrybrew to your user PATH? y/n [n]

y

Unhandled Exception: System.UnauthorizedAccessException: Access to the registry key 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck)
   at BerryBrew.Berrybrew.PathSet(List`1 path)
   at BerryBrew.Berrybrew.Config()
   at BBConsole.bbconsole.Main(String[] args)

**Comment by stevieb9** [comment]
Unfortunately, at this time, berrybrew requires administrative privileges.

Later today I will be working on correcting this deficiency, by putting
everything in the User PATH target.

However, if a system perl (Strawberry Perl or ActiveState) has been
installed, without admin privileges, berrybrew won't work as Machine
(System) PATH takes precedence over User PATH (thanks, Windows!).

I'll also be adding much better exception handling.

Steve

**Comment by stevieb9** [comment]
This exception is now caught and handled gracefully in 617dff88ef51

I've created a user_based branch to track my work in allowing berrybrew to work with non-admin privileges

**Comment by cmfrolick** [comment]
Thank you.

I can see there being need for local (current console only), user, and system level path changes. We have some batch files that run standard cpanm installs of modules for our environment. It would be nice to be able to change only the current console to run those, so the execute can then be run against multiple test versions.
