### ISSUE TITLE
WARNING! orphaned perl installations

### ISSUE THREAD

**Issue by niceperl** [stevieb9/berrybrew#52]
After I have downloaded `berrybrew`and run `bin\berrybrew config`, I got this message:

```
WARNING! orphaned perl installations:

  bin

  data
```

What does it mean? Before the brerrybrew download, I uninstalled the strawberry perl 5.18.0 my labtop had.

**Comment by stevieb9** [comment]
It means that you have a 'bin' and 'data' directory in the Perl
installation dir (c:\berrybrew), and berrybrew thinks they are
installations of Perl that shouldn't be there (ie. they are not registered
as Perl installations).

You can remove those directories (manually move/delete them, or delete them
with `berrybrew clean orphan`), or ignore the warning. Over the weekend,
I'll add in provisions to allow non-perl-install directories to be ignored.

Do those directories need to be there? May I ask for what? I'm just curious
as to the use-case(s), so I can add in provisions for situations where
rogue directories are required in the installation dir.

**Comment by niceperl** [comment]
I created by hand these directories. I downloaded the ZIP file you provided and then extract to c:\berrybrew folder. They didn't exists before that

I don't know if I followed a bad procedure to install berrybrew, I didn't use git clone command

**Comment by niceperl** [comment]
When I run `c:> berrybrey clean orphan` as admin, I get an unhandled exception: path access denied 'bbapi.dll' 

```
Excepción no controlada: System.UnauthorizedAccessException: Acceso denegado a la ruta de acceso 'bbapi.dll'.
   en System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   en System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   en BerryBrew.Berrybrew.CleanOrphan()
   en BerryBrew.Berrybrew.Clean(String subcmd)
   en BBConsole.bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
Oh, ok. I'll need to clarify the documentation.

Don't unzip the zip file into that directory. The c:\berrybrew dir is
specifically for the installations of Perl. Unzip the zip file to somewhere
else, such as `c:\users\username` or the like, so you'll have
`c:\users\username\berrybrew`. Under there will be data and bin. The
c:\berrybrew directory is created automatically by berrybrew when it is
first initialized.

After you've cleaned out the c:\berrybrew directory, do the unzip to an
alternate location, manually remove berrybrew from your environment
variable's PATH, then re-initialize berrybrew from its new location.

**Comment by niceperl** [comment]
Ok, I have done it and now it works!
Another question: are you planning to support the "lib" command ?
Thanks
