### ISSUE TITLE
URL/checksum mismatch issue while installing 5.22.2_32

### ISSUE THREAD

**Issue by atcroft** [stevieb9/berrybrew#53]
Attempting to install 5.22.2_32, and encountered the following error:
```
PS C:berrybrew> berrybrew install 5.22.2_32
Downloading http://strawberryperl.com/download/5.22.2.1/strawberry-perl-5.22.2.1-32bit.zip to C:\berrybrew\installed\temp\strawberry-perl-5.22.2.1-32bit.zip
Confirming checksum ...
Error checksum of downloaded archive
C:\berrybrew\installed\temp\strawberry-perl-5.22.2.1-32bit.zip
does not match expected output
expected: 6c750c56a4eccf3b5f77af56e4cee572c360a1c2
     got: 804a0dff0a3e4a9b3ac37c4495894467cccd35ec
Whould you like berrybrew to delete the corrupted download file? y/n [n]
PS C:\berrybrew> berrybrew install 5.22.2_32
Confirming checksum ...
Error checksum of downloaded archive
```
When I checked the Strawberry Perl website (http://strawberryperl.com/releases.html), I found both checksums. When I examined the links, I found that the URL for 804a0dff0a3e4a9b3ac37c4495894467cccd35ec checksum referred to the file [strawberry-perl-5.22.2.1-32bit.zip](http://strawberryperl.com/download/5.22.2.1/strawberry-perl-5.22.2.1-32bit.zip), while the 6c750c56a4eccf3b5f77af56e4cee572c360a1c2 checksum referred to the file [strawberry-perl-5.22.2.1-32bit-portable.zip](http://strawberryperl.com/download/5.22.2.1/strawberry-perl-5.22.2.1-32bit-portable.zip). Examining data\perls.json, I found that the section for 5.22.2_32 points to the -32bit.zip file, rather than the -32bit-portable.zip file (as all other _32 sections except those for PDL version).
```
[
    {
        "name" : "5.22.2_32",
        "file" : "strawberry-perl-5.22.2.1-32bit.zip",
        "url"  : "http://strawberryperl.com/download/5.22.2.1/strawberry-perl-5.22.2.1-32bit.zip",
        "ver"  : "5.22.2",
        "csum" : "6c750c56a4eccf3b5f77af56e4cee572c360a1c2"
    },
]
```
My instance of Berrybrew was installed from a file downloaded from this site using [this link](https://github.com/stevieb9/berrybrew/archive/master.zip) as a .zip file on 2016-10-29, with size of 522,925 bytes, and an sha1sum of d27f906e868c7fd7d320f4149d908248e867e53a.

Also, (possibly a simplistic question, but) is it possible to re-attempt an install without having to re-download the file again (for example, if you downloaded it via a different method)?

**Comment by stevieb9** [comment]
Hey @atcroft , I'm just about to commit the fix to the problem you've pointed out (thanks!), but before I did I wanted to let you know that if you fetch a perl zip file manually (or have already installed and removed previously), the files reside in `c:\berrybrew\temp` until manually deleted (or using `berrybrew clean temp`, and we'll use the files in there instead of downloading again.

**Comment by atcroft** [comment]
Thank you for your hard work on this project! 

(And thank you for the information about the files. I was curious where/if they were retained.)
