### ISSUE TITLE
Unhandled Exception if berrybrew is installed in c:\berrybrew

### ISSUE THREAD

**Issue by ggearhead** [stevieb9/berrybrew#55]
I installed the zip version of berrybrew on my windows 10 machine. I made the mistake of installing it into c:\berrybrew so I moved it to a different location and removed the setting in the path env var. Well now berrybrew will not run. I keep getting this error.

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\berrybrew\data\config.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at BerryBrew.Berrybrew.JsonParse(String type, Boolean raw)
   at BerryBrew.Berrybrew..ctor()
   at BBConsole.bbconsole.Main(String[] args)

C:\bin\berrybrew>

I've tried deleting everything and reloading, checked the path variable to make sure it was not set with berrybrew and it still insists on looking for c:\berrybrew\data\config.json

Is there some other file in perhaps the AppData dir?

**Comment by stevieb9** [comment]
So you've deleted the entire installation directory, and removed all traces
of berrybrew and perl from %PATH%?

Try it again, then download another copy of the zip file, and extract it
somewhere else (anywhere but c:\berrybrew), then cd into the berrybrew
directory, and run `bin\berrybrew.exe config`. That should re-configure
everything properly.

If that fails, I will start up my win10 VM and do some testing.

**Comment by stevieb9** [comment]
Also, I'll write in some checks to attempt to prevent this from happening in the future (ie. fail to install itself into `c:\berrybrew`.

**Comment by ggearhead** [comment]
Sorry this is rather long but I wanted to give as much info as possible.
I've tried a number of different install dirs and the problem seems to be isolated to one particular directory, c:\bin. I first did what you said and deleted the berrybrew files from my system, made sure the env var did not have berrybrew in the PATH and downloaded a new berrybrew.zip. I then did the following:
1. Installed berrybrew to c:\temp2.
2. cd to c:\temp2 and ran "bin\berrybrew.exe config" (as admin). Result -> no unhandled exception error but I do get a different error.
Here is the screen output:
      This is berrybrew, version
      1.08

      Would you like to add berrybrew to PATH? y/n [n]

      y

      Error adding berrybrew to PATH

When I check the PATH var, c:\temp2\bin has been added and that is all.
Also, c:\berrybrew dir has been created by the program. Should c:\berrybrew be added to the PATH var also?

3. Clean the system of berrybrew again and remove c:\temp2\bin from PATH var.
4. Install berrybrew in c:\bin\berrybrew
5. cd to c:\bin\berrybrew and ran "bin\berrybrew.exe config" (as admin). Result -> unhandled exception.
6. Clean system again as in 3. above.
7. Install berrybrew in c:\bin
8. cd to c:\bin and ran "bin\berrybrew.exe config" (as admin). Result -> unhandled exception.
9. Clean system again as in 3. above.
10. Install berrybrew in c:\bin\bb
11. cd to c:\bin\bb and ran "bin\berrybrew.exe config" (as admin). Result -> unhandled exception.
12. Clean system again as in 3. above.
13. Install berrybrew in c:\bb
14. cd to c:\bb and ran "bin\berrybrew.exe config" (as admin). Result -> this works the same as 2. above.

So it seems that I cannot install berrybrew to the c:\bin dir. 
When I check the PATH var it has c:\bb\bin for the berrybrew install, but c:\berrybrew is not in the PATH var. As a work around, I can add c:\berrybrew to the PATH var if it's supposed to be there. Please advise. Thanks.

**Comment by stevieb9** [comment]
Thanks for your patience.

I can't see any reason why it won't install into c:\bin. Again, when I have
some cycles this week, I'll do some testing specifically on win10.

The c:\berrybrew directory won't show up in the PATH env var when you
initially run the 'config' routine. It only puts the PATH to itself in
there. After you've installed an instance of perl (eg: berrybrew install
5.24.0_64), then c:\berrybrew will show up in PATH, appended with the
specifics of the perl installation directory. Likewise, removing a perl
instance will then remove that specific entry from PATH as its no longer
needed.

After doing an install that does go well, can you install an instance of
perl and check whether things work ok?

- berrybrew install 5.24.0_64
- berrybrew switch 5.24.0_64
- close current cmd window
- open new cmd window
- perl -v

**Comment by ggearhead** [comment]
Confirmed, it does work when following your instructions. Thank you for the help.
