### ISSUE TITLE
Add 5.24.1 PDL edition

### ISSUE THREAD

**Issue by shawnlaffan** [stevieb9/berrybrew#57]
Strawberry perl also has a PDL edition.  It would be good if that were listed as well for the 5.24.1 and 5.22.3 versions.

(There are currently 5.24.0 and 5.22.2 PDL editions available, so this will be consistent with the previous releases). 

Thanks,
Shawn.

**Comment by stevieb9** [comment]
I will go back through and add them. I've gotten feedback that they aren't
used widely, but if one person makes the request, it's worth it.

Thanks.

**Comment by shawnlaffan** [comment]
Thanks Steve.  

Regards,
Shawn.

**Comment by stevieb9** [comment]
Closing, the appreciated PR was merged and I forgot to close the ticket.

**Comment by shawnlaffan** [comment]
Thanks again.

Shawn.

**Comment by stevieb9** [comment]
You're very welcome. I honestly haven't even tested it yet ;)  I'm just
setting up my new multi-location build/test environments, and am getting
set to get my hands dirty on some of the other issues, and feature includes.

If you have any other suggestions, I'd be glad to hear them.

Steve
