### ISSUE TITLE
berrybrew use

### ISSUE THREAD

**Issue by pryrt** [stevieb9/berrybrew#77]
As referenced in [one of my comments in #15](https://github.com/stevieb9/berrybrew/issues/15#issuecomment-286176780), and hinted at in PR #74 , I am experimenting with a `berrybrew use` that will take one (or more) perl version, and spawn new windows (or possibly also have an embedded `cmd.exe` in the current window, if I can get that working) for each selected perl version.

I know that windows PATH handling is PITA, but for the spawned-window-per-used-version, it will hopefully not be too annoying.  Getting an inline version will be harder, and I might not figure it out in my initial version...

You can spy on my progress in my [DevelopUse](https://github.com/pryrt/berrybrew/tree/DevelopUse) branch in my fork.

**Comment by stevieb9** [comment]
This feature has been merged from PR #80.
