### ISSUE TITLE
"use" doesn't complain (or do anything) if the requested version isn't installed

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#83]
The best option here I think is to have it warn the user that the version they are wanting to load is unavailable.

The other option would be to force an automatic install, but I think it's best to not encroach on a user's time if they simply want to fire one that's already installed.

@pryrt do you have any input here? What are your thoughts?

**Comment by pryrt** [comment]
Good catch. Looking at your update, I concur.
